import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import PageHeader from "@/components/PageHeader";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/sonner"
import { GithubIcon } from "lucide-react";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-500 ease-in-out`}

      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange={false}>

          <PageHeader />

          {children}
          <Toaster position="top-center" richColors />

          <Separator className='border-2' />
          <footer className='flex justify-between items-center p-6 flex-col gap-4 sm:flex-row'>

            <p>InspoLog</p>

            <a href="https://github.com/MUMEi-28/inspo-log" className="hover:underline transition-all duration-300" target='_blank'>View Github</a>
            <p>© {new Date().getFullYear()} InspoLog. <br /> All rights reserved.</p>
          </footer>
        </ThemeProvider>
      </body>
    </html >
  );
}
